changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
    - title: Other Highlights ✨ 
      labels:
        - "*"
      exclude:
        labels:
          - dependabot
    - title: Security Upgrades 🔐
      labels:
        - dependabot

